name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Composer install
        run: composer install --no-progress --no-ansi --prefer-dist

      - name: PHP CodeSniffer
        run: composer phpcs

      - name: PHPStan
        run: composer phpstan

      - name: Run tests
        run: composer test
