name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-24.04

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GH_REGISTRY_USERNAME }}
          password: ${{ secrets.GH_REGISTRY_PAT }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          provenance: false
          context: ./docker
          push: true
          tags: |
            ghcr.io/typesetterio/typesetter-cli:${{ github.sha }}
            ghcr.io/typesetterio/typesetter-cli:latest
